<?php
/**
 * Created by PhpStorm.
 * User: Yaroslav
 * Date: 09.09.2018
 * Time: 18:24
 */

$lang = [
    'en' => [
        'close' => 'Close',
        'distance' => 'Distance',
        'fast_parking' => 'FAST PARKING',
        'filter' => 'FILTER',
        'search' => 'SEARCH',
        'search_result' => 'SEARCH RUSULT',
        'refresh' => 'Refresh',
        'apply_filter' => 'Apply Filter',
        'new_search' => 'New Search',
        'day' => 'Day',
        'mon-fry' => 'Mon-Fry',
        'sat' => 'Sat',
        'sun' => 'Sun',
        'time' => 'Time',
        'from' => 'from',
        'from_time' => 'from',
        'to' => 'to',
        'hours' => 'Hours',
        'min' => 'min',
        'h' => 'h',
        'km' => 'km',
        'm' => 'm'
    ],
    'ru' => [
        'close' => 'Закрыть',
        'distance' => 'Расстояние',
        'fast_parking' => 'БЫСТРЫЕ ПАРКОВКИ',
        'filter' => 'ФИЛЬТР',
        'search' => 'ПОИСК',
        'search_result' => 'РУЗЕЛЬТАТ ПОИСКА',
        'refresh' => 'Обновить',
        'apply_filter' => 'Применить Фильтр',
        'new_search' => 'Новый поиск',
        'day' => 'Дни',
        'mon-fry' => 'Пн-Пт',
        'sat' => 'Суб',
        'sun' => 'Вс',
        'time' => 'Время',
        'from' => 'от',
        'from_time' => 'с',
        'to' => 'по',
        'hours' => 'Часы',
        'min' => 'мин',
        'h' => 'ч',
        'km' => 'км',
        'm' => 'м'
    ],
    'uk' => [
        'close' => 'Закрити',
        'distance' => 'Відстань',
        'fast_parking' => 'ШВИДКІ ПАРКОВКИ',
        'filter' => 'ФІЛЬТР',
        'search' => 'ПОШУК',
        'search_result' => 'РУЗЕЛЬТАТ ПОШУКУ',
        'refresh' => 'Оновити',
        'apply_filter' => 'Застосувати Фільтр',
        'new_search' => 'Новий Пошук',
        'day' => 'Дні',
        'mon-fry' => 'Пн-Пт',
        'sat' => 'Суб',
        'sun' => 'Нд',
        'time' => 'Час',
        'from' => 'від',
        'from_time' => 'з',
        'to' => 'по',
        'hours' => 'Години',
        'min' => 'хв',
        'h' => 'год',
        'km' => 'км',
        'm' => 'м'
    ],
    'fi' => [
        'close' => 'lähikuva',
        'distance' => 'etäisyys',
        'fast_parking' => 'nopea pysäköinti',
        'filter' => 'suodatin',
        'search' => 'haku',
        'search_result' => 'hakutulos',
        'refresh' => 'Päivitys',
        'apply_filter' => 'Sovelletaan Suodatinta',
        'new_search' => 'Uusi Haku',
        'day' => 'Päivää',
        'mon-fry' => 'My-Fry',
        'sat' => 'Sat',
        'sun' => 'Sun',
        'time' => 'Aika',
        'from' => 'from',
        'from_time' => 'from',
        'to' => 'to',
        'hours' => 'Tuntia',
        'min' => 'min',
        'h' => 'h',
        'km' => 'km',
        'm' => 'm'
    ]
];